#ifndef __SYSTEM_STATE_H
#define __SYSTEM_STATE_H


typedef enum
{
    SYSTEM_STATE_INIT,
    SYSTEM_STATE_CALIBRATION,
    SYSTEM_STATE_BYPASS,
    SYSTEM_STATE_RING_IDLE,
    SYSTEM_STATE_RING_ACTIVE,
    SYSTEM_STATE_RING_BRAKE_OVERRIDE,
    SYSTEM_STATE_ERROR
} SystemState_t;

#endif /* __SYSTEM_STATE_H__ */